### ISSUE TITLE
This is not the official source of MADB

### ISSUE THREAD

**Issue by camalot** [quamotion/madb#7]
You should state that this is a fork. The name madb is the name of the official project. There are official nuget packages, but you have created your own. While you did provide myself as an author, again, it is using the madb, which is the name of the official project, but not the ID on nuget. 

As it stands, you are violating the license:

6. Trademarks.
This License does not grant permission to use the trade names, trademarks, service marks, or product names of the Licensor, except as required for reasonable and customary use in describing the origin of the Work and reproducing the content of the NOTICE file.

Please make it known that is is a fork of the original project and change the name of the nuget package id.

**Comment by qmfrederik** [comment]
Hi @camalot,

Thanks for reaching out to us!

We've initially created this project to fix some issues we've reported against the original madb project and provided you a link back to this project as a means to share the fixes we've implemented (see e.g. work item [21787](http://madb.codeplex.com/workitem/21787), [21763](http://madb.codeplex.com/workitem/21763), [21658](http://madb.codeplex.com/workitem/21658) & [21653](http://madb.codeplex.com/workitem/21653)).

As it stands, we've spent quite a lot of time refactoring the code base, adding unit tests and making the code base StyleCop compliant (see #4 and #5). We've done that based on some of the requirements we had.

I think our version of the codebase has diverged sufficiently from yours to warrant a rename. We'll update the name of the project and the NuGet packages.

Net, here's what we'll do:
- Rename the project and NuGet packages, which should avoid any confusion with madb (and madbee, and Managed.Adb)
- Keep or add copyright notices to all source files
- Mention you in the [COPYRIGHT](https://github.com/quamotion/madb/blob/master/COPYRIGHT) file at the root of the repository
let us know whether this satisfies your request.

Since we're talking about licensing and attribution, we tried to make sure we properly license and attribute the code contained in this package (see e.g. the [COPYRIGHT](https://github.com/quamotion/madb/blob/master/COPYRIGHT)) file.

Here's what we found so far:
* madb is a .NET port of the [Java version of the ddmlib project](https://android.googlesource.com/platform/tools/base/+/master/ddmlib/), so copyright should be attributed to The Android Open Source Project, too
* madb includes (e.g. [BEBinaryReader.cs](https://github.com/camalot/madb/blob/master/trunk/Managed.AndroidDebugBridge/Managed.AndroidDebugBridge/IO/BEBinaryReader.cs)) [dicom-cs](http://sourceforge.net/projects/dicom-cs/) which is licensed under the LGPLv2 license. We've removed this dependency as it seems this would force this code to be licensed under the LGPLv2 rather than the Apache license.
* madb includes (e.g. [BigEndianConverter.cs](https://github.com/camalot/madb/blob/master/trunk/Managed.AndroidDebugBridge/Managed.AndroidDebugBridge/Conversion/BigEndianBitConverter.cs)) [MiscUtil](http://jonskeet.uk/csharp/miscutil/) which is licensed under the Apache license, so requires attribution, too. We've removed this file in our codebase.

Do you know of any other codebase that's included in madb or any other license that may apply to the code in madb?

Let me know if you have any further questions or comments,

Frederik.

**Comment by camalot** [comment]
Thank you Frederik. It isn't my name that is the issue, which you have have in place in most of the source that I looked at already, it is the lack of a link to the original source: either on the original codeplex site (http://madb.codeplex.com) or the current project home at github (http://github.com/camalot/madb). 

I was actually happy to see someone else actively working on this, as it is just a side project for me. The issue I had was that you have a nuget package and the project using the original project name, without stating that it is a fork of another project. Honestly, I would rather to see this code merged back in to the original project. So I guess what I am saying is, if you provide a link to the original (which if it the project was on github when you forked it, it would be there) I am fine with the name, and would even be ok with the nuget package using that name as the ID. This would eliminate the issues with renaming a nuget package ID too.

I am not aware of any other licenses that apply to code.

**Comment by qmfrederik** [comment]
Hi Ryan,

I've prepared #8, which includes a link to the GitHub project where you do the active development, and also renames the library and NuGet packages to SharpAdbClient to avoid naming conflicts.
That should resolve this issue for now.

I'm always happy to look into how we can merge back our changes to the main madb repository. Thing is, we've made a lot of changes and I want to make sure you're comfortable with them before we embark on trying to convert this into a pull request.

Madb has worked really well for us so far (thanks!), but we've had issues from time to time - you can find most of them on Codeplex.

What we came to realize is that madb does a lot more than what we require for now. For example, the `Device` class provides a lot of functionality (say, support for exploring the entire file system or support for BusyBox) which we don't use right now, and which would bite us from time to time.

What we currently need is a thin implementation of the adb protocol which provides support for the basic adb commands - anything you can do with the command line version of adb, say.

So the first thing we did was to split madb in two - a part we thought we'd need, and another part, which we dubbed `Managed.Adb.Extensions`, which provides additional features which we don't currently use.

Then we set out to make sure the code in the 'core' madb library is testable (we currently have about 30% code coverage and are looking to increase that) and complies with our internal code standards - mainly StyleCop compliance. StyleCop also has a rule that enforces copyright headers at the top of each file, so that's why you saw us (well, StyleCop really) add copyright headers to files we didn't even change.

The changes are a bit intrusive from time to time - for example, the `AdbHelper` class has mainly disappeared and has been split in an `AdbSocket` (which takes care of sending low-level messages) and `AdbClient` (which takes care of the actual command). The `DeviceMonitor` and `SyncService` wrap around the `AdbSocket`. The `Device` class has moved to the Extensions project and been replaced with a `DeviceData` object, which basically only holds the information adb has on the device (such as name, status). You can still create a `Device` object; that would just wrap around the `DeviceData` object and provide additional functionality.

If that's something you'd like to merge back to madb, we'd need to figure out the how to do that. For example, our root folders are different (our `/` maps to your `/trunk`), and we migrated the code from Codeplex separately. Our commit [9d7b110](https://github.com/quamotion/madb/commit/9d7b11098a2d05e4bb5e09c10a040d34b765a8cb) is your [3e58c47](https://github.com/camalot/madb/commit/3e58c47976794aab94bed0db85ee6106762a6df9).

Cheers,

Frederik.

**Comment by qmfrederik** [comment]
Hi @camalot 

We pulled the 'madb' package from NuGet and re-published with our own, and updated the name of this project. That should fix your initial request.

Happy to keep the conversation on how to merge back these changes going -- feel free to comment on this issue or create a separate one for that.

Cheers,
