### ISSUE TITLE
Device Disconnect

### ISSUE THREAD

**Issue by jmcleangithub** [quamotion/madb#83]
With AdbClient.Instance.Connect I can connect to a device at a particular host address.  How can I force the disconnect (e.g,  adb disconnect <ip>) via the AdbClient?  I expected a Disconnect method to exist alongside the Connect method.

We are working with multiple connected devices and don't want to shutdown the device in order to disconnect from adb server.

**Comment by qmfrederik** [comment]
We don't have one yet, looking at the [commandline.cpp](https://github.com/android/platform_system_core/blob/9d2e688b9ab5abdb3d6c191907a5f44cb3c9833f/adb/commandline.cpp#L1517) source code, it looks the underlying command is `host:disconnect:%s`.

The way to add this would be to add a function which is almost exactly the same as [Connect](https://github.com/quamotion/madb/blob/master/SharpAdbClient/AdbClient.cs#L465) to `AdbClient`.

Feel free to send a PR :), otherwise I'll probably have a look at it in the near future.

**Comment by jmcleangithub** [comment]
Thank you for confirming.  I wasn't sure if I was missing it.  We will look at your suggestion and add the function that's needed.
